# Generated by Django 6.0.1 on 2026-01-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_certification_leadership'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (optional)', null=True),
        ),
    ]
