# Generated by Django 6.0.1 on 2026-01-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_start_date_alter_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contribution',
            field=models.TextField(blank=True, help_text='Specific contribution to the project'),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_command',
            field=models.CharField(blank=True, help_text='1-2 commands to run/demo', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='metrics',
            field=models.CharField(blank=True, help_text='Key metrics (latency, throughput, etc.)', max_length=200),
        ),
    ]
