# Generated by Django 6.0.1 on 2026-08-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_contribution_project_demo_command_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('PROG', 'Programming'), ('CYBER', 'Cybersecurity'), ('NET', 'Networking'), ('SYS', 'Systems'), ('TOOLS', 'Security & Development Tools'), ('WEBDB', 'Databases / Web')], max_length=10),
        ),
    ]
